// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('d:/ThucTap/App/node_modules/react');
var { Component } = React;
var ReactNative = require('d:/ThucTap/App/node_modules/react-native');
var { AppRegistry } = ReactNative;
var entryPoint = require('d:/ThucTap/App/index.js');
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('App', appParameters);
});